apiVersion: v1
kind: Pod
metadata:
  name: linux-container-with-snapshot
spec:
  volumes:
    - name: snapshot-volume
      emptyDir: {}
  containers:
    - name: main-container
      image: zim95/ssh_ubuntu:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: snapshot-volume
          mountPath: /mnt/snapshot
      # command or args can include a script to create the tar.gz when needed

    - name: snapshot-sidecar
      image: zim95/snapshot_sidecar:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: snapshot-volume
          mountPath: /mnt/snapshot

    - name: status-sidecar
      image: zim95/status_sidecar:latest
      securityContext:
        privileged: true
      volumeMounts:
        - name: snapshot-volume
          mountPath: /mnt/snapshot
