# Development deployment for snapshot job (used for dev testing)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-job-development
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapshot-job-development
  template:
    metadata:
      labels:
        app: snapshot-job-development
    spec:
      containers:
      - name: snapshot-job-development
        image: ${REPO_NAME}/snapshot-job-development:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
            ephemeral-storage: "4Gi"
        env:
        - name: CONTAINER_ID
          value: "${CONTAINER_ID}"
        - name: POD_NAME
          value: "${POD_NAME}"
        - name: NAMESPACE_NAME
          value: "${NAMESPACE}"
        - name: REPO_NAME
          value: "${REPO_NAME}"
        - name: REPO_PASSWORD
          value: "${REPO_PASSWORD}"
        - name: DB_HOST
          value: "${DB_HOST}"
        - name: DB_PORT
          value: "${DB_PORT}"
        - name: DB_USERNAME
          value: "${DB_USERNAME}"
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"
        - name: DB_DATABASE
          value: "${DB_DATABASE}"
        - name: SNAPSHOT_PATH
          value: "${SNAPSHOT_PATH}"
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        hostPath:
          path: ${HOSTPATH}
          type: DirectoryOrCreate
